### ISSUE TITLE
Add a way to temporarily disable for a single visit

### ISSUE THREAD

**Issue by Crote** [raicem/impulse-blocker#10]
When this addon is used to block a website, a user may sometimes still need to navigate to that website from an external link. For example, I block reddit.com, but a web search on some programming stuff might still link to a page on reddit.com, requiring me to disable the addon. However, the addon is now fully disabled, allowing one to visit any site you want. It would be useful if it were possible to "override" the block for a single visit.

**Comment by Crote** [comment]
This might be a useful alternative:

Instead of blocking immediately, delay the visit by a certain amount of time, increasing exponentially.

For the first visit, delay by 10 seconds, and double this time for every subsequent visit of a blocked page. Using a separate timer, halve this delay every, say, 30 minutes or so (should probably be configurable).

While a timer is running, sites cannot be removed from the block list and the blocker cannot be disabled. If the user _really_ wants to visit it, they can always just disable the whole addon.

It may also be useful to always re-enable the blocker after a certain number of minutes, preventing the user from accidentally leaving it disabled.

Issue to be solved: what to do if the user repeatedly tries to visit the same blocked site while the delay is running? It might be useful to prevent the addon for adding to the timer for repeated infractions.

Thoughts, @raicem?

**Comment by giomasce** [comment]
I like this feature proposal in its original description.

**Comment by raicem** [comment]
I've implemented a feature for pausing the extension. You will be able to pause it for 5/10 mins etc. So its only sort of similar to what you wanted to implement.

**Comment by Crote** [comment]
I noticed the update on my desktop, but my phone doesn't yet have it. At first glance, this will probably work fine so I'm closing this. I'll try it out over the next couple of days and let you know if there are any issues with it.

Potential, first-thought, improvements:
- a 1-minute pause
- differently coloured icon when paused

**Comment by raicem** [comment]
OK. Thank you very much. Any feedback especially on the mobile browser side is appreciated. I have not had a chance to test it on the phone that much. 

I learned that you can force Firefox to update extensions [more frequently](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Updates#Testing_Automatic_Updating). Maybe this technique works on the phone as well.
