### ISSUE TITLE
Which Branch To Commit To?

### ISSUE THREAD

**Issue by prail** [raicem/impulse-blocker#22]
So I'd like to make some changes to merge here but, I'm unsure about which branch I should commit to for development so I don't mess up the latest stable release branch. I assume this would be `development` and `master` is stable. Is this correct?

**Comment by raicem** [comment]
Yes that is correct. You can commit to `development`. I would tag it and merge it to master for uploading to the AMO. I left the branches a bit messy. Sorry about that. Deleted the unused `develop` branch. Thank you for your contribution.
