### ISSUE TITLE
Improved icons

### ISSUE THREAD

**Issue by pkonneker** [raicem/impulse-blocker#23]
Hello,

The current icons are usable but not super easy to follow.

Was considering modifying (with my admittedly programmer level art skills) some icons from an open source set for use here.

Maybe a shield with a 1 or 0 for enabled and disabled?
See: https://icons8.com/icon/852/shield
Or https://feathericons.com/ (filter on shield)

**Comment by raicem** [comment]
Yep the PR is here: #24 

I think we can find an original solution just by browing the copyright-free icon sites and find something that suits us. 

If we are gonna change the logo, what do you think about releasing an update with this current, temporary logo? I think we cause a little bit of confusion if we change it two times. Just an idea I just had 😄

**Comment by pkonneker** [comment]
Yeah it'd probably be silly to change them so much in rapid succession.

**Comment by pkonneker** [comment]
Maybe a wall icon?
