### ISSUE TITLE
Chrome compatibility

### ISSUE THREAD

**Issue by pkonneker** [raicem/impulse-blocker#26]
Currently running firefox, but I'd be interested in a chrome port if I ever started using that as my main browser (I tend to hop to whichever one is currently most stable/fast).

How interested are you in having compatibility with both browsers?

I have a branch with the bulk of the edits if you want to check it out. It's mostly just that chrome doesn't support native promises in extensions apis. (yet?) So you have to use callbacks.

**Comment by raicem** [comment]
Well, the reason I made this extension was that there were no Firefox alternatives for the Chrome extension called [Go Fucking Work](https://chrome.google.com/webstore/detail/go-fucking-work/hibmkkpfegfiinilnlabbfnjcopdiiig?hl=es-419nnn).

Therefore, I ignored the chrome support at that time.  

Using callbacks would feel like a step back at this point. So I don't know. If you already did the work, I can happily check it out.

**Comment by pkonneker** [comment]
Ah gotcha. That is definitely true. Not sure why chrome isn't supporting promises. 

I did most of the work. It's not a huge edit, though. I mostly did it for the learning so it's not much of a sunk cost. Feel free to check it out or not. No sweat. Plenty of other things I could do that would be more useful.

https://github.com/pkonneker/impulse-blocker/pull/1/files

**Comment by raicem** [comment]
After giving it a thought I think its not worth it. Since now Chrome wants to alter WebRequest API that we are using to only support non-dynamic matching it may require some custom code in the future. So I'm closing this issue. Many thanks!
