### ISSUE TITLE
Add support for Firefox for Android

### ISSUE THREAD

**Issue by nikwen** [raicem/impulse-blocker#3]
Please add support for Firefox for Firefox. :)

Currently, I can install the plugin and it is enabled, but I cannot configure it.

**Comment by raicem** [comment]
Hey there, thanks for using the extension and the feedback. I'm aware of that issue. I think Android does not have default settings screen like the Firefox desktop. So I will write on my own. Definately on the list of todos.

**Comment by jayesh-bhoot** [comment]
>> I think Android does not have default settings screen like the Firefox desktop. So I will write on my own.

I use Firefox Nightly on Android. The settings UI, as seen on the desktop version, appears there. I can also add websites to the list. However, while I swear that the add-on also blocked websites successfully a few days ago (on Firefox Nightly Android), it doesn't do that anymore.

May be this means that same settings UI (but responsive) could work on both desktop and mobile in future versions.

**Comment by raicem** [comment]
Wow, didn't know that one was coming. Thanks for letting me know. 

I think I will keep this issue open. Even though now we have this screen on mobile, having a custom settings will help in the future. Then I can directly link it from menubar popup and add other stuff.

**Comment by raicem** [comment]
New Firefox Android is now allows users to access the addons setting page (as pointed above). In addition to that @Crote added a shortcut for reaching this settings page from the toolbar (You can see active addons in the main menu). So this should not be a issue anymore.
