### ISSUE TITLE
Icon Hard to See In Dark Mode

### ISSUE THREAD

**Issue by prail** [raicem/impulse-blocker#30]
I've just recently switched to the dark mode version of Firefox. The transparency in the icon makes it hard to see against the dark background. Here's a screenshot showing what I mean:

![impulsevisibility](https://user-images.githubusercontent.com/16790483/48734593-b40e7d80-ebfa-11e8-9b12-e109c1d8f069.png)

**Comment by pkonneker** [comment]
Ah good call. We should mimic the gray tone the default firefox icons are using.

**Comment by raicem** [comment]
Hey, @pkonneker  
Do you want to make further changes to the icons or should I just publish it with the your last revision?
