### ISSUE TITLE
Extension does not work on Firefox ESR

### ISSUE THREAD

**Issue by HouyiTheArcher** [raicem/impulse-blocker#35]
For some reason extension GUI (both toolbar pop-up and settings page) does not work. Settings page shows for a second and then turns blank white. Firefox version is 60.5.2esr

**Comment by raicem** [comment]
Thanks for reporting. You closing the issue made me think that the issue is now gone? I'm in a place where there is no proper internet connection. So I can only check the ESR version next week.

**Comment by HouyiTheArcher** [comment]
Yep, the issue is fixed for now. For some reason a I had to re-install add-on in order to make it work again (turning off and on did not help). Something similar also happened once for me with another extension, so it might be ESR issue.
