### ISSUE TITLE
Enable / Disable broken on Android

### ISSUE THREAD

**Issue by Crote** [raicem/impulse-blocker#38]
This has been broken since (I believe) 1.0, but I never got around to filing a bug report.
So, the addon *mostly* works on Android, but anything which turns it off (the "off" button in the popup, the pause buttons in the popup, and the off button in the settings) does not actually work correctly: it prints the following error message to the console: `Error: browser.browserAction.setIcon is not a function`. After this, it does disable, but the GUI never updates, so it looks af if nothing happens. It is also impossible to re-enable it, except by restarting.
This makes perfect sense, because `setIcon` is not implemented on Android, as there isn't any icon to set. In 0.5, this probably also happened, but setting the icon just happened to always be the very last thing done when changing the status, so it worked by accident.
In 1.0, `start` and `pause` do other stuff after setting the icon, so the status change fails before it is finished. Checking whether it's a function instead of undefined before calling it will probably fix it.

**Comment by raicem** [comment]
Crote, thank you. I know there was a problem with the Android. I just got a hold of an Android phone last week. However, could not find a time to debug it. I will take a look at it asap.

**Comment by raicem** [comment]
This problem is fixed with the [1.1.2 release](https://github.com/raicem/impulse-blocker/releases/tag/1.1.2).

The problem was Firefox Android not supporting the function to change the icon. This [commit ](https://github.com/raicem/impulse-blocker/commit/b14650109470efb663bddfce6ae607458940eef2) fixed it.
