### ISSUE TITLE
Not working at all?

### ISSUE THREAD

**Issue by LunarFantom** [raicem/impulse-blocker#39]
I downloaded and installed the app, and I can see the little icon at the top right when I browse, but its not blocking any of the blacklisted sites. Does it not work with Adblock Plus or something other such thing?

**Comment by raicem** [comment]
Which platform are you using? Desktop or Firefox Mobile? Some websites are really difficult to block  (such as Twitter #33) with the current method but other than that I have no reports of it not working with the Adblock Plus.

**Comment by LunarFantom** [comment]
Nah, I have a lot of sites on my blacklist-list and its not working for any of them. It's version 1.1.0

**Comment by pkonneker** [comment]
If you click the icon does it say on or off?

**Comment by LunarFantom** [comment]
It says its on

**Comment by raicem** [comment]
Well, this sucks. @LunarFantom may I ask which browser version are you on? I'll try to replicate it somehow.

**Comment by LunarFantom** [comment]
Says this is 66.0.5 (64-bit)

**Comment by LunarFantom** [comment]
Wait, firefox JUST updated and now it works. Huh.

**Comment by raicem** [comment]
Well, I could not replicate it. I'm happy that it started working but kinda sad that we won't know why that happened. Closing the issue. Thanks for reporting it @LunarFantom.
