### ISSUE TITLE
The add-on does not always work

### ISSUE THREAD

**Issue by jayesh-bhoot** [raicem/impulse-blocker#5]
When I say 'doesn't work', I mean the blocked websites load without any obstruction from Impulse Blocker.

I haven't yet found a definite pattern when it works or doesn't work. First I thought it is because I use Nightly releases. But the regular release too shows the same symptoms. 

This problem occurs both on Linux and Windows.

I know I am not giving out much, but this is all I have right now. I will post further details as and when I find some.

**Comment by raicem** [comment]
I actually thought the same thing the other day at work. Realized the websites were not getting blocked. And I forgot about it until I saw your issue now :) So thanks for the heads up. I'll start to deal with it immediately. Hopefully I can fix it today.

**Comment by raicem** [comment]
Huh, I saw one error and extension indeed stopped working but I could not understand why and can not reproduce the error now. I'll use exclusively Firefox and this extension this week to catch it again.

**Comment by jayesh-bhoot** [comment]
I will enable the extension and test for a couple of days on my part, and report here. Let's keep the issue open till we are sure.

**Comment by jayesh-bhoot** [comment]
It works for now. The good part is that it works not only in Firefox Nightly, but also Firefox Nightly on Android. You may want to mark the add-on as Android compatible too. The UI feels desktop-y on the phone, but it works well.

This doesn't mean that it would work on Firefox Stable too as well. Unfortunately, I cannot verify that, not at least until weekend.

**Comment by raicem** [comment]
I have found out the extension is not initialized when Firefox is first started. It only begins to block websites after you interact with it somehow e.g. adding removing sites or turning the extension on/off. I fixed it and sent an update again. 

To be honest, I have no idea how that ever worked. Code was pretty dumb 😄

**Comment by raicem** [comment]
Hey @jayesh-bhoot, I also fixed an issue with opening a blocked link in new tab. Version 0.2.4 will fix that. Hoping to close this issue soon after this update.

**Comment by jayesh-bhoot** [comment]
> Hey @jayesh-bhoot, I also fixed an issue with opening a blocked link in new tab. Version 0.2.4 will fix that. Hoping to close this issue soon after this update.

I had noticed this. Code can produce some pretty funny and unexpected behaviour!

Anyway, everything seems to work fine now. We could close this issue.

**Comment by raicem** [comment]
Many thanks for the feedback. Getting ready for that Firefox 57 release.
