### ISSUE TITLE
Explicitly specify fonts

### ISSUE THREAD

**Issue by Mattwmaster58** [raicem/impulse-blocker#68]
Some sites have their own styles which get used by the popup leading to inconsistent looking popups. An explicitly specified font would fix this if I'm not mistaken. I'd probably be able to come up with something, any suggestions for an implementation?

**Comment by raicem** [comment]
Hi @Mattwmaster58, I'm afraid I don't understand what do you mean by:

> Some sites have their own styles which get used by the popup leading to inconsistent looking popups. 

Do you mean a website's CSS affects our popup? That very weird. Do you have examples that I can take a look at?

> I'd probably be able to come up with something, any suggestions for an implementation?

We do have `font-family: Arial, Helvetica, sans-serif;` on `popup.css`. Maybe we should change that to the [system font](https://css-tricks.com/snippets/css/system-font-stack/)?

**Comment by Mattwmaster58** [comment]
Huh, this makes me think the site is doing something weird. I've seen the behaviour on https://krunker.io

**Comment by Mattwmaster58** [comment]
I think this catch-all CSS rule is responsible
```css
* {
    ...
    font-family: gamefont;
    ...
}
```

**Comment by raicem** [comment]
I don't see that happening :thinking: The screenshot you have sent does not look like the Impulse Blocker interface though. I'm confused. 

Here is what I see:
![Screenshot from 2021-01-15 18-35-23](https://user-images.githubusercontent.com/10389957/104746560-7ec13400-5760-11eb-880a-59163131bd89.png)

**Comment by Mattwmaster58** [comment]
Oh snap, I got the names confused! My bad
